export const API_ROUTES = {
  ADMIN: {
    ADMINLOGIN: "/admin/login",
    ADMINLOGOUT: "/admin/logout",
    CANDIDATES: "/admin/candidates",
    BLOCK_UNBLOCK_CANDIDATE: "/admin/candidates/block-unblock",
    EMPLOYERS: "/admin/employers",
    BLOCK_UNBLOCK_EMPLOYER: "/admin/employers/block-unblock",
    VERIFY_EMPLOYER: "/admin/employers",
    REJECT_EMPLOYER: (id: string) => `/admin/employers/${id}/reject`,
    JOBS: "/admin/jobs",
    DASHBOARD_ANALYTICS: "/admin/analytics/dashboard",
  },
  AUTH: {
    SIGNUP: "/auth/signup",
    LOGIN: "/auth/login",
    ME: "/auth/me",
    SEND_OTP: "/auth/send-otp",
    VERIFY_OTP: "/auth/verify-otp",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh-token",
  },
  CANDIDATE: {
    PROFILE: "/candidate/profile",
    JOBS: "/jobs",
    APPLY: (jobId: string) => `/candidate/jobs/${jobId}/apply`,
    APPLICATIONS: "/candidate/applications",
    APPLICATION_BY_ID: (id: string) => `/candidate/applications/${id}`,
  },
  EMPLOYER: {
    PROFILE: "/employer/profile",
    JOBS: "/employer/jobs",
    JOB: (jobId: string) => `/employer/jobs/${jobId}`,
    JOB_CLOSE: (jobId: string) => `/employer/jobs/${jobId}/close`,
    APPLICATIONS: "/employer/applications",
    UPDATE_APPLICATION_STATUS: (applicationId: string) =>
      `/employer/applications/${applicationId}/status`,
    ANALYTICS: "/employer/analytics",
  },
  JOBS: {
    PUBLIC: "/jobs",
    PUBLIC_BY_ID: (id: string) => `/jobs/public/${id}`,
    SAVE: (jobId: string) => `/jobs/save/${jobId}`,
    UNSAVE: (jobId: string) => `/jobs/save/${jobId}`,
    SAVED: "/jobs/saved",
  },
  SUBSCRIPTION: {
    CREATE_ORDER: "/employer/subscription/create-order",
    VERIFY_PAYMENT: "/employer/subscription/verify-payment",
    HISTORY: "/employer/subscription/history",
  },
  INTERVIEWS: {
    CANDIDATE: "/interviews/candidate",
    EMPLOYER: "/interviews/employer",
    UPDATE_STATUS: (id: string) => `/interviews/employer/${id}/status`,
  },
  INTERVIEW_ROUNDS: {
    BASE: "/interviews/rounds",
    APPLICATION: (id: string) => `/interviews/rounds/application/${id}`,
    CANDIDATE: "/interviews/rounds/candidate",
    EMPLOYER: "/interviews/rounds/employer",
    BY_ID: (id: string) => `/interviews/rounds/${id}`,
    STATUS: (id: string) => `/interviews/rounds/${id}/status`,
    RESCHEDULE: (id: string) => `/interviews/rounds/${id}/reschedule`,
    CANCEL: (id: string) => `/interviews/rounds/${id}/cancel`,
    VALIDATE: (id: string, token: string) =>
      `/interviews/rounds/${id}/validate/${token}`,
  },
  INTERVIEW_FEEDBACK: {
    ROUND: (roundId: string) => `/interviews/rounds/${roundId}/feedback`,
    APPLICATION: (applicationId: string) =>
      `/interviews/rounds/feedback/application/${applicationId}`,
    SUMMARY: (roundId: string) =>
      `/interviews/rounds/${roundId}/feedback/summary`,
    CANDIDATE_ROUND: (roundId: string) =>
      `/interviews/rounds/${roundId}/feedback/candidate`,
    BY_ID: (id: string) => `/interviews/feedback/${id}`,
    SHARE: (id: string) => `/interviews/feedback/${id}/share`,
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    STATS: "/notifications/stats",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
    DELETE: (id: string) => `/notifications/${id}`,
  },
  CHAT: {
    BASE: "/chat",
    CREATE: "/chat/create",
    MY_CHATS: "/chat/my-chats",
    MESSAGE: "/chat/message",
    MESSAGES: (chatId: string) => `/chat/${chatId}/messages`,
    MARK_READ: (chatId: string) => `/chat/${chatId}/read`,
  },
  VIDEO_CALL: {
    INITIATE: "/video-call/initiate",
    END: "/video-call/end",
    STATUS: (interviewId: string) => `/video-call/status/${interviewId}`,
  },
  FEEDBACK: {
    BASE: "/feedback",
    PUBLIC: "/feedback/public",
    FEATURED: "/feedback/featured",
    ADMIN: "/feedback/admin",
    ADMIN_BY_ID: (id: string) => `/feedback/admin/${id}`,
  },
} as const;

export const FRONTEND_ROUTES = {
  ADMIN_DASHBOARD: "/dashboard",
  ADMINLOGIN: "/signin",
  LOGIN: "/login",
  HOME: "/",
  SIGNUP: "/signup",
  VERIFY_OTP: "/verify",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  AUTHSUCCESS: "/auth-success",
  CANDIDATEPROFILE: "/profile",
  EMPLOYERPROFILE: "/company",
  JOBVIEW: "/jobs",
  JOBDETAILS: "/job/:id",
  EMPLOYERJOBS: "/employer/jobs",
  EMPLOYERAPPLICANTS: "/applicants",
  EMPLOYERANALYTICS: "/analytics",
  EMPLOYERBILLING: "/subscriptions",
  EMPLOYERINTERVIEWS: "/interviews",
  EMPLOYERINTERVIEWDETAIL: "/interviews/:id",
  EMPLOYERREPORTS: "/employer/reports",
  EMPLOYERSETTINGS: "/setting",
  EMPLOYERNOTIFICATIONS: "/notification",
  CANDIDATEAPPLICATIONS: "/applications",
  APPLICATIONDETAILS: "/applications/:id",
  CANDIDATENOTIFICATIONS: "/notifications",
  CANDIDATESAVEDJOBS: "/saved",
  CANDIDATESETTINGS: "/settings",
  CANDIDATEINTERVIEW: "/interview",
  CANDIDATEINTERVIEWDETAIL: "/interview/:id",
  ADMINEMPLOYERS: "/employers",
  ADMINCANDIDATES: "/candidates",
  ADMINCANDIDATEVIEW: "/candidates/view/:id",
  ADMINEMPLOYERVIEW: "/employers/view/:id",
  ADMINJOBS: "/admin/jobs",
  ADMINNOTIFICATIONS: "/admin/notifications",
  ADMINSETTINGS: "/admin/settings",
  ADMINFEEDBACK: "/admin/feedback",
  CHAT: "/chat",
  MESSAGES: "/messages",
  CANDIDATEMESSAGES: "/candidate/messages",
  EMPLOYERMESSAGES: "/employer/messages",
  VIDEOCALL: "/video",
} as const;
