export const API_ROUTES = {
  ADMIN: {
    ADMINLOGIN: "/admin/login",
    ADMINLOGOUT: "/admin/logout",
    CANDIDATES: "/admin/candidates",
    BLOCK_UNBLOCK_CANDIDATE: "/admin/candidates/block-unblock",
    EMPLOYERS: "/admin/employers",
    BLOCK_UNBLOCK_EMPLOYER: "/admin/employers/block-unblock",
    VERIFY_EMPLOYER: "/admin/employers",
    REJECT_EMPLOYER: (id: string) => `/admin/employers/${id}/reject`,
    JOBS: "/admin/jobs",
  },
  AUTH: {
    SIGNUP: "/auth/signup",
    LOGIN: "/auth/login",
    ME: "/auth/me",
    SEND_OTP: "/auth/send-otp",
    VERIFY_OTP: "/auth/verify-otp",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh-token",
  },
  CANDIDATE: {
    PROFILE: (id: string) => `/candidate/${id}`,
    JOBS: "/jobs",
    APPLY: (candidateId: string, jobId: string) =>
      `/candidate/${candidateId}/jobs/${jobId}/apply`,
    APPLICATIONS: "/candidate/applications",
    APPLICATION_BY_ID: (id: string) => `/candidate/applications/${id}`,
  },
  EMPLOYER: {
    PROFILE: (id: string) => `/employer/${id}`,
    JOBS: (id: string) => `/employer/jobs/${id}`,
    JOB: (id: string, jobId: string) => `/employer/jobs/${id}/${jobId}`,
    JOB_CLOSE: (employerId: string, jobId: string) =>
      `/employer/jobs/${employerId}/${jobId}/close`,
    APPLICATIONS: (employerId: string) =>
      `/employer/${employerId}/applications`,
    UPDATE_APPLICATION_STATUS: (employerId: string, applicationId: string) =>
      `/employer/${employerId}/applications/${applicationId}/status`,
  },
  JOBS: {
    PUBLIC: "/jobs",
    PUBLIC_BY_ID: (id: string) => `/jobs/public/${id}`,
    SAVE: (jobId: string) => `/jobs/save/${jobId}`,
    UNSAVE: (jobId: string) => `/jobs/save/${jobId}`,
    SAVED: "/jobs/saved",
  },
  SUBSCRIPTION: {
    CREATE: "/subscription/create",
    CURRENT: "/subscription/current",
    CANCEL: "/subscription/cancel",
  },
  INTERVIEWS: {
    CANDIDATE: "/candidate/interviews",
    EMPLOYER: "/employer/interviews",
  },
} as const;

export const FRONTEND_ROUTES = {
  ADMIN_DASHBOARD: "/admin-dashboard",
  ADMINLOGIN: "/admin-signin",
  LOGIN: "/login",
  HOME: "/",
  SIGNUP: "/signup",
  VERIFY_OTP: "/verify",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  AUTHSUCCESS: "/auth-success",
  CANDIDATEPROFILE: "/candidate-profile",
  EMPLOYERPROFILE: "/employer-profile",
  JOBVIEW: "/jobs",
  JOBDETAILS: "/jobs/:id",
  EMPLOYERJOBS: "/employer/jobs",
  EMPLOYERAPPLICANTS: "/employer/applicants",
  EMPLOYERANALYTICS: "/employer/analytics",
  EMPLOYERRBILLING: "/employer/subscription",
  EMPLOYERINTERVIEWS: "/employer/interviews",
  EMPLOYERREPORTS: "/employer/reports",
  EMPLOYERSETTINGS: "/employer/settings",
  EMPLOYERNOTIFICATIONS: "/employer/notifications",
  CANDIDATEAPPLICATIONS: "/candidate/applications",
  APPLICATIONDETAILS: "/candidate/applications/:id",
  CANDIDATENOTIFICATIONS: "/candidate/notifications",
  CANDIDATESAVEDJOBS: "/candidate/saved-jobs",
  CANDIDATESETTINGS: "/candidate/settings",
  CANDIDATEINTERVIEW: "/candidate/interview",
  ADMINEMPLOYERS: "/admin-employers",
  ADMINCANDIDATES: "/admin-candidates",
  ADMINCANDIDATEVIEW: "/admin-candidates/view/:id",
  ADMINEMPLOYERVIEW: "/admin-employers/view/:id",
  ADMINJOBS: "/admin-jobs",
  ADMINNOTIFICATIONS: "/admin-notifications",
  ADMINSETTINGS: "/admin-settings",
  CHAT: "/chat",
  VIDEOCALL: "/video",
} as const;
