export enum ERROR_MESSAGES {
  SERVER_ERROR = "An error occurred, please try again later.",
  VALIDATION_ERROR = "Validation error occurred.",
  EMAIL_EXIST = "Email already exists.",
  USER_NAME_EXIST = "Username already exists.",
  EMAIL_NOT_EXIST = "Email not found.",
  OTP_EXPIRE = "Your One-Time Password has expired. Please request a new one.",
  INVALID_OTP = "The OTP you entered is incorrect. Please try again.",
  NO_COOKIES = "Please register first.",
  INVALID_CREDENTIALS = "Invalid credentials. Please check your email or password.",
  REFRESH_TOKEN_REQUIRED = "Refresh token required.",
  NOT_AUTHENTICATED = "Not authenticated. Please log in again.",
  GOOGLE_LOGIN_FAILED = "Google login failed. Please try again.",
  GOOGLE_AUTH_ERROR = "Error during Google authentication.",
  GOOGLE_TOKEN_INVALID = "Invalid Google token. Please try again.",
  REQUIRED_ID = "Id required.",
  RESUME_REQUIRED = "Resume is required",
  USER_BLOCKED = "User blocked by admin.",
  INVALID_REFRESH_TOKEN = "Invalid refresh token",
  NO_REFRESH_TOKEN = "No valid refresh token found",
  EMPLOYER_NOT_FOUND = "Employer not found",
  CLOUDINARY_ERROR = "Failed to upload file to Cloudinary",
  EMPLOYER_VERIFY_ERROR = "Cannot verify employer: CIN number and Business License are required.",
  EMPLOYER_REJECTION_ERROR = "Cannot send rejection mail to Employer.",
  INVALID_DEADLINE = "Invalid deadline date",
  FUTURE_DEADLINE = "Deadline must be in the future",
  EMPLOYER_VERIFICATION_FAILED = "You cannot perform this action. Complete your company verification to post or manage jobs.",
  EMPOYER_ID = "Employer ID is required",
  JOB_ID = "Job ID is required",
  JOB_NOT_FOUND = "Job not found",
  DEADLINE_PASSED = "Application deadline has passed",
  JOB_INACTIVE = "Job is no longer active",
  JOB_CONFLICT = "Already applied to this job",
  AUTHENTICATION = "Authentication required",
  APPLICATION_NOT_FOUND = "Application not found",
  FAILED_LOADING = "Failed to load updated application",
  ENV_ERROR = "Razorpay credentials not configured. Please add RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET to your .env file",
  RAZORPAY_ERROR = "Error creating Razorpay order",
  SIGNATURE_ERROR = "Invalid signature",
  UPLOAD_ERROR = "Failed to upload file",
  PAYMENT_VERIFICATION_ERROR = "Payment verification failed",
  SUBSCRIPTION_HISTORY_ERROR = "Failed to fetch subscription history",
  NOTIFICATION_NOTFOUND = "Notification not found",
  NOTIFICATION_ID_REQUIRED = "Notification ID is required",
}

export enum SUCCESS_MESSAGES {
  USER_REGISTERED = "User registered successfully.",
  LOGIN_SUCCESS = "Login successful.",
  LOGOUT_SUCCESS = "Logout successful.",
  SEND_OTP_TO_MAIL = "OTP sent to registered email successfully.",
  OTP_VERIFIED = "OTP verified successfully.",
  PASSWORD_RESET_SUCCESS = "Password reset successfully.",
  GOOGLE_LOGIN_SUCCESS = "Google login successful.",
  GOOGLE_LOGOUT_SUCCESS = "Google logout successful.",
  FETCH_SUCCESS = "Fetched all users.",
  STATUS_UPDATED = "Status updated successfully.",
  CANDIDATE_FETCHED = "Candidate profile fetched successfully.",
  EMPLOYER_FETCHED = "Employer profile fetched successfully.",
  CANDIDATE_UPDATED = "Candidate profile updated successfully",
  EMPLOYER_UPDATED = "Employer profile updated successfully",
  JOB_POST_SUCCESS = "Job posted successfully",
  JOB_UPDATED = "Job updated",
  APPLICATION_CREATED = "Application submitted successfully",
  APPLICATIONS_FETCHED = "Application fetched successfully",
  INTERVIEWS_FETCHED = "Interviews fetched successfully",
  INTERVIEW_CANCELLED = "Interview cancelled successfully",
  INTERVIEW_RESCHEDULED = "Interview rescheduled successfully",
  SUBSCRIPTION_ACTIVATED = "Subscription activated successfully",
  NOTIFICATION_READ = "Notification marked as read",
  ALL_READ = "All notifications marked as read",
  NOTIFICATION_DELETED = "Notification deleted",
  NOTIFICATIONS_FETCHED = "Notifictaions fetched successfully",
  NOTIFICATION_STATS_FETCHED = "Notification status fetched",
  CHAT_INITIATED = "Chat initiated successfully",
  CHATS_FETCHED = "Chats fetched successfully",
  MESSAGE_SENT = "Message sent successfully",
  MESSAGES_FETCHED = "Messages fetched successfully",
  MESSAGES_MARKED_READ = "Messages marked as read",
  VIDEO_CALL_INITIATED = "Video call initiated successfully",
  VIDEO_CALL_ENDED = "Video call ended successfully",
  VIDEO_CALL_STATUS_FETCHED = "Call status retrieved successfully",
}

export enum NotificationType {
  EMPLOYER_VERIFICATION_SUBMITTED = "employer_verification_submitted",
  VERIFICATION_APPROVED = "verification_approved",
  VERIFICATION_REJECTED = "verification_rejected",
  NEW_APPLICATION = "new_application",
  APPLICATION_WITHDRAWN = "application_withdrawn",
  APPLICATION_REVIEWED = "application_reviewed",
  APPLICATION_SHORTLISTED = "application_shortlisted",
  APPLICATION_REJECTED = "application_rejected",
  INTERVIEW_SCHEDULED = "interview_scheduled",
  INTERVIEW_CANCELLED = "interview_cancelled",
}

export enum NOTIFICATION_MESSAGES {
  APPLICATION_REVIEWED_TITLE = "Application Reviewed",
  APPLICATION_REVIEWED_MESSAGE = "Your application for {{jobTitle}} at {{companyName}} has been reviewed.",
  APPLICATION_SHORTLISTED_TITLE = "You've Been Shortlisted!",
  APPLICATION_SHORTLISTED_MESSAGE = "Congratulations! You've been shortlisted for {{jobTitle}} at {{companyName}}.",
  APPLICATION_REJECTED_TITLE = "Application Update",
  APPLICATION_REJECTED_MESSAGE = "Thank you for applying to {{jobTitle}} at {{companyName}}. We've decided not to move forward at this time. Best of luck!",
  APPLICATION_HIRED_TITLE = "You're Hired!",
  APPLICATION_HIRED_MESSAGE = "Congratulations! You've been hired for {{jobTitle}} at {{companyName}}! Welcome aboard!",
  APPLICATION_UPDATED_TITLE = "Application Updates",
  APPLICATION_UPDATED_MESSAGE = "Your application for {{jobTitle}} at {{companyName}} has been updated.",
  INTERVIEW_SCHEDULED_TITLE = "Interview Scheduled",
  INTERVIEW_SCHEDULED_MESSAGE = "Your interview for {{jobTitle}} is scheduled at {{companyName}}. Check email for informations",
  INTERVIEW_CANCELLED_TITLE = "Interview Cancelled",
  INTERVIEW_CANCELLED_MESSAGE = "Your interview for {{jobTitle}} has been cancelled.",
  ADMIN_VERIFICATION_REQUEST_TITLE = "New Verification Request",
  ADMIN_VERIFICATION_REQUEST_MESSAGE = "{{employerName}} submitted verification documents.",
  ACCOUNT_VERIFICATION = "Your account has been verified successfully",
  VERIFICATION_REJECTED = "Your verification request was rejected",
  USER_BLOCKED = "Your account has been blocked by admin.",
  USER_UNBLOCKED = "Your account has been unblocked. You can now log in.",
}

export enum USER_ROLES {
  CANDIDATE = "Candidate",
  EMPLOYER = "Employer",
  ADMIN = "Admin",
}

export type UserRole = `${USER_ROLES}`;
